---
- name: "Download logback.xml"
  become: true
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    validate_certs: false
    force: "yes"
  loop:
  - { url: "{{ git_conf_files_path }}/{{ env }}/{{ module }}/logback.xml", dest: "{{ files_conf_path }}/{{ module }}/logback.xml", owner: "root", group: "root", mode: "644"}
  tags: application.properties

- name: "Download application.properties"
  become: true
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    validate_certs: false
    force: "yes"
  loop:
  - { url: "{{ git_conf_files_path }}/{{ env }}/{{ module }}/application.properties", dest: "{{ files_conf_path }}/{{ module }}/application.properties", owner: "root", group: "root", mode: "644"}
  tags: logback.xml